name: al_fep
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  # Core Python
  - python=3.10
  - pip
  
  # Scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  
  # Machine Learning
  - pytorch>=1.12.0
  - transformers
  - tensorboard
  
  # Molecular modeling and cheminformatics
  - rdkit>=2022.03.0
  - openmm>=7.7.0
  - mdtraj>=1.9.0
  - pymol-open-source
  
  # Reinforcement Learning
  - gym
  
  # Data visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  
  # Jupyter and development
  - jupyter
  - jupyterlab
  - notebook
  - ipywidgets
  
  # Docking and molecular dynamics
  - openbabel
  
  # Development tools
  - black
  - pytest
  - pytest-cov
  - flake8
  - mypy
  
  # Pip packages (not available in conda)
  - pip:
    - wandb
    - stable-baselines3
    - mols2grid
    - selfies
    - meeko
